apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: label
                operator: In
                values:
                - test
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - flaskapp
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: flaskapp
        image: sunbeth/assignment:4
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: flaskapp
spec:
  type: ClusterIP
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

